-- ============================================================================
-- ⚠️ DEPRECADO (JOGOS v2) — NAO RODAR ESTE ARQUIVO.
--
-- game_leaderboard e game_my_rank foram SUPERADAS pela v3 em
-- supabase/games-difficulty.sql (ranking por score EFETIVO com dificuldade +
-- multiplicador, que o frontend vivo exige — lib/games.ts le entry.difficulty).
-- Esta versao v2 rankeia por score CRU; reaplicar este arquivo REVERTE a v3 em
-- silencio e quebra o placar (o `create or replace` aqui tem a mesma assinatura
-- (text,int,text) da v3, entao sobrescreve mesmo).
--
-- A tabela game_scores + indices + RLS vivem em supabase/games.sql.
-- Mantido so como registro historico.
-- ============================================================================
