-- ============================================================================
-- ⚠️ DEPRECADO (v1) — NAO RODAR ESTE ARQUIVO.
--
-- Esta era a 1a versao do cron de lembretes (so vacinas; auth via
-- app.service_role_key + Bearer, esquema que NAO e mais usado). Foi inteiramente
-- superada. As fontes canonicas hoje sao:
--   - FUNCAO notify_due_care(): supabase/push-harden.sql (v94, 3 categorias +
--     dedup + header x-petsocial-secret exigido pela edge endurecida).
--   - TABELA push_notifications_sent + AGENDAMENTO do cron: supabase/push-reminders-v2.sql.
--
-- Reaplicar este arquivo REVERTERIA notify_due_care pra versao antiga (sem o
-- segredo -> edge responde 401 -> push para) e exigiria o ALTER DATABASE com
-- service_role_key que nem existe mais. Mantido so como registro historico.
-- ============================================================================
